#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

Best=0
while [ $Best -lt 10 ];
do
        echo "Best School"
	if [ $Best -eq 8 ];
	then
		echo "Hi"
	fi
        ((Best++))
done
